[target.x86_64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
]

[target.i686-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
]

[target.aarch64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
]

[registries]
UefiTestFeed = { index = "sparse+https://pkgs.dev.azure.com/microsoft/MsUEFI/_packaging/UefiTestFeed/Cargo/index/" }

[source.crates-io]
replace-with = "UefiTestFeed"
